version: '3.8'

networks:
  microservices_net:
    driver: bridge

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    volumes:
      - ./user-service/users.db:/app/users.db
    networks:
      - microservices_net
    environment:
      - FLASK_ENV=production

  task-service:
    build: ./task-service
    ports:
      - "5001:5001"
    environment:
      - USER_SERVICE_URL=http://user-service:5000
      - FLASK_ENV=production
    volumes:
      - ./task-service/tasks.db:/app/tasks.db
    depends_on:
      - user-service
    networks:
      - microservices_net

  nginx-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./admin:/usr/share/nginx/html/admin  # Carpeta para la interfaz /admin
    depends_on:
      - user-service
      - task-service
    networks:
      - microservices_net